#!/usr/bin/env bats

load 'helpers/test_helper.bash'
load 'helpers/mock_env.bash'

setup() {
  setup_test_env
}

teardown() {
  teardown_test_env
}

@test "compose-rules omits metadata and empty agent overrides by default" {
  local output_path
  output_path="${TEST_TMP}/AGENTS.md"

  run bash "$(repo_root)/ai-rules/scripts/compose-rules.sh" codex "${output_path}"

  [ "$status" -eq 0 ]
  [ -f "${output_path}" ]
  [[ ! "$(cat "${output_path}")" == *"Auto-generated by ai-rules/scripts/compose-rules.sh."* ]]
  [[ ! "$(cat "${output_path}")" == *"Sources:"* ]]
  [[ ! "$(cat "${output_path}")" == *"Codex Overrides"* ]]
  [[ ! "$(cat "${output_path}")" == *$'\n---\n'* ]]
  [[ "$(cat "${output_path}")" == *"## Instruction Priority"* ]]
}

@test "compose-rules emits metadata only when requested" {
  local output_path
  output_path="${TEST_TMP}/AGENTS.md"

  run bash "$(repo_root)/ai-rules/scripts/compose-rules.sh" codex --with-metadata "${output_path}"

  [ "$status" -eq 0 ]
  [ -f "${output_path}" ]
  [[ "$(cat "${output_path}")" == *"Auto-generated by ai-rules/scripts/compose-rules.sh."* ]]
  [[ "$(cat "${output_path}")" == *"Sources: ai-rules/base/global.md"* ]]
  [[ ! "$(cat "${output_path}")" == *"Codex Overrides"* ]]
}
