[tools]
r = "4.5.2"
neovim = "0.12"
zellij = "0.43"
ripgrep = "15"
fd = "10.4.2"
bat = "0.26.1"
zoxide = "0.9.9"
atuin = "18.16.1"
yazi = "26.5.6"
delta = "0.19.2"
lazygit = "0.59"
lazydocker = "0.25"
oxker = "0.13"
gitui = "0.28"
"aqua:dlvhdr/gh-dash" = "4.24.1"
mprocs = "0.9.3"
just = "1.51.0"
watchexec = "2.5.1"
process-compose = "1.110.0"
"cargo:pueue" = "4.0.4"
github-cli = "2"
ruff = "0.15"
uv = "0.10"
yt-dlp = "2025.03.31"
azure = "2"
gcloud = "543"
terraform = "1.14"
"cargo:tree-sitter-cli" = "0.26.8"
typst = "0.14"
shellcheck = "0.11"
bats = "1.13"
"aqua:quarto-dev/quarto-cli" = "1.9"
"github:aristocratos/btop" = "1.4"

[settings]
cargo.binstall = false
