[tools]
neovim = "0.11"
zellij = "0.43"
ripgrep = "15"
lazygit = "0.59"
gitui = "0.28"
github-cli = "2"
ruff = "0.15"
uv = "0.10"
yt-dlp = "2025.03.31"
azure = "2"
gcloud = "543"
terraform = "1.14"
typst = "0.14"
shellcheck = "0.11"
bats = "1.13"
