set nocompatible
set encoding=utf-8
set fileencodings=ucs-bom,utf-8,cp932,euc-jp,latin1
scriptencoding utf-8

if filereadable($VIMRUNTIME . '/defaults.vim')
  unlet! skip_defaults_vim
  source $VIMRUNTIME/defaults.vim
endif

filetype plugin indent on
if has('syntax')
  syntax enable
endif

let mapleader = "\<Space>"
set number relativenumber
set tabstop=2 softtabstop=2 shiftwidth=2 expandtab
set autoindent backspace=indent,eol,start
set ignorecase smartcase incsearch hlsearch
set hidden wildmenu
set wrap linebreak
if exists('+breakindent')
  set breakindent
endif
set formatoptions+=mM
set nrformats-=octal
set laststatus=2 showcmd
set timeoutlen=500 ttimeoutlen=100
set nobackup nowritebackup noswapfile
set background=dark
if has('mouse')
  set mouse=a
endif

let s:undo_dir = expand('~/.vim/vim/undo')
if has('persistent_undo') && isdirectory(s:undo_dir)
  let &undodir = s:undo_dir
  set undofile
endif

nnoremap <silent> <Esc> :nohlsearch<CR>
nnoremap <C-h> <C-w>h
nnoremap <C-j> <C-w>j
nnoremap <C-k> <C-w>k
nnoremap <C-l> <C-w>l

" Resolve the symlink so this also works without linking the runtime directory.
let s:dotfiles_root = fnamemodify(resolve(expand('<sfile>:p')), ':h:h')
let &runtimepath = escape(s:dotfiles_root . '/vim', '\,') . ',' . &runtimepath
call dotfiles#clipboard#setup(s:dotfiles_root)
