#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "${SCRIPT_DIR}/../.." && pwd)"

BASE_FILE="${ROOT_DIR}/ai-rules/base/global.md"
AGENTS_DIR="${ROOT_DIR}/ai-rules/agents"

usage() {
  cat <<'USAGE'
Usage:
  ai-rules/scripts/compose-rules.sh all
  ai-rules/scripts/compose-rules.sh <agent> [output_path] [layer ...]
  ai-rules/scripts/compose-rules.sh <agent> [-o output_path] [-l layer ...]
  ai-rules/scripts/compose-rules.sh <agent> [--with-metadata] [output_path] [layer ...]

Examples:
  ai-rules/scripts/compose-rules.sh codex
  ai-rules/scripts/compose-rules.sh codex ~/.codex/AGENTS.md
  ai-rules/scripts/compose-rules.sh claude claude/CLAUDE.md python django
  ai-rules/scripts/compose-rules.sh gemini -o ~/.gemini/GEMINI.md -l typescript -l nextjs
  ai-rules/scripts/compose-rules.sh codex --with-metadata /tmp/AGENTS.md

Notes:
  - layer は次の順で解決されます.
    1) 既存ファイルパス
    2) リポジトリ相対パス
    3) ai-rules/stacks/<layer>.md
    4) ai-rules/frameworks/<layer>.md
    5) ai-rules/projects/<layer>.md
USAGE
}

if [[ ! -f "${BASE_FILE}" ]]; then
  echo "Error: base rule file not found: ${BASE_FILE}" >&2
  exit 1
fi

WITH_METADATA=0

target_for_agent() {
  case "$1" in
    codex) echo "AGENTS.md" ;;
    gemini) echo "GEMINI.md" ;;
    claude) echo "claude/CLAUDE.md" ;;
    *)
      echo "Error: unknown agent '$1'" >&2
      return 1
      ;;
  esac
}

override_for_agent() {
  case "$1" in
    codex) echo "${AGENTS_DIR}/codex.md" ;;
    gemini) echo "${AGENTS_DIR}/gemini.md" ;;
    claude) echo "${AGENTS_DIR}/claude.md" ;;
    *)
      echo "Error: unknown agent '$1'" >&2
      return 1
      ;;
  esac
}

expand_path() {
  local path="$1"
  case "${path}" in
    "~") echo "${HOME}" ;;
    "~/"*) echo "${HOME}/${path#~/}" ;;
    *) echo "${path}" ;;
  esac
}

resolve_layer_file() {
  local layer="$1"

  if [[ -f "${layer}" ]]; then
    echo "${layer}"
    return 0
  fi
  if [[ -f "${ROOT_DIR}/${layer}" ]]; then
    echo "${ROOT_DIR}/${layer}"
    return 0
  fi

  local candidate
  for candidate in \
    "${ROOT_DIR}/ai-rules/stacks/${layer}.md" \
    "${ROOT_DIR}/ai-rules/frameworks/${layer}.md" \
    "${ROOT_DIR}/ai-rules/projects/${layer}.md"; do
    if [[ -f "${candidate}" ]]; then
      echo "${candidate}"
      return 0
    fi
  done

  echo "Error: layer not found '${layer}'" >&2
  return 1
}

file_has_content() {
  local path="$1"
  [[ -f "${path}" ]] && grep -q '[^[:space:]]' "${path}"
}

render_one() {
  local agent="$1"
  local output_path="$2"
  shift 2

  local override_file
  local target_path
  local source_note
  local doc_file
  local layer
  local layer_file
  local doc_files=()
  local layer_files=()
  local source_parts=("ai-rules/base/global.md")
  local first_doc=1

  override_file="$(override_for_agent "${agent}")"
  target_path="$(expand_path "${output_path}")"

  if [[ "${target_path}" != /* ]]; then
    target_path="${ROOT_DIR}/${target_path}"
  fi

  doc_files+=("${BASE_FILE}")

  if file_has_content "${override_file}"; then
    doc_files+=("${override_file}")
    source_parts+=("ai-rules/agents/${agent}.md")
  fi

  for layer in "$@"; do
    layer_file="$(resolve_layer_file "${layer}")"
    if file_has_content "${layer_file}"; then
      layer_files+=("${layer_file}")
      source_parts+=("${layer}")
    fi
  done

  mkdir -p "$(dirname "${target_path}")"

  {
    if [[ "${WITH_METADATA}" -eq 1 ]]; then
      source_note="${source_parts[*]}"
      source_note="${source_note// / + }"
      echo "<!-- Auto-generated by ai-rules/scripts/compose-rules.sh. -->"
      echo "<!-- Sources: ${source_note} -->"
      echo
    fi

    for doc_file in "${doc_files[@]}" "${layer_files[@]}"; do
      if [[ "${first_doc}" -eq 0 ]]; then
        echo
        echo "---"
        echo
      fi
      cat "${doc_file}"
      first_doc=0
    done
    echo
  } > "${target_path}"

  echo "Generated ${target_path}"
}

if [[ $# -eq 0 ]] || [[ "${1:-}" == "all" ]]; then
  render_one codex "$(target_for_agent codex)"
  render_one gemini "$(target_for_agent gemini)"
  render_one claude "$(target_for_agent claude)"
  exit 0
fi

if [[ "${1:-}" == "-h" ]] || [[ "${1:-}" == "--help" ]]; then
  usage
  exit 0
fi

agent="${1:-}"
shift

case "${agent}" in
  codex|gemini|claude) ;;
  *)
    echo "Error: unknown agent '${agent}'" >&2
    usage >&2
    exit 1
    ;;
esac

output_path="$(target_for_agent "${agent}")"
layers=()

while [[ $# -gt 0 ]]; do
  case "$1" in
    -h|--help)
      usage
      exit 0
      ;;
    --with-metadata)
      WITH_METADATA=1
      shift
      ;;
    -o|--output)
      if [[ $# -lt 2 ]]; then
        echo "Error: --output requires a value" >&2
        exit 1
      fi
      output_path="$2"
      shift 2
      ;;
    -l|--layer)
      if [[ $# -lt 2 ]]; then
        echo "Error: --layer requires a value" >&2
        exit 1
      fi
      layers+=("$2")
      shift 2
      ;;
    *)
      if [[ "${output_path}" == "$(target_for_agent "${agent}")" ]] && \
         ([[ "$1" == "~"* ]] || [[ "$1" == /* ]] || [[ "$1" == *"/"* ]] || [[ "$1" == *.md ]]); then
        output_path="$1"
      else
        layers+=("$1")
      fi
      shift
      ;;
  esac
done

if [[ ${#layers[@]} -gt 0 ]]; then
  render_one "${agent}" "${output_path}" "${layers[@]}"
else
  render_one "${agent}" "${output_path}"
fi
