shell = "zsh"

[plugins.zsh-defer]
github = "romkatv/zsh-defer"

[templates]
PATH = 'export PATH="$PATH:{{ dir }}"'
defer = "{{ hooks?.pre | nl }}{% for file in files %}zsh-defer source \"{{ file }}\"\n{% endfor %}{{ hooks?.post | nl }}"
defer-with-delay = "{{ hooks?.pre | nl }}{% for file in files %}zsh-defer -t 0.1 source \"{{ file }}\"\n{% endfor %}{{ hooks?.post | nl }}"
fzf-install = "{{ dir }}/install --bin > /dev/null \n[[ ! $PATH =~ {{ dir }} ]] && export PATH=\"$PATH:{{ dir }}/bin\"\n"
fzf-source = "{% for file in files %}source \"{{ file }}\"\n{% endfor %}"

[plugins.compinit]
inline = "autoload -Uz compinit && zsh-defer compinit"

[plugins.colors]
inline = "autoload -Uz colors && zsh-defer colors"

[plugins.dotfiles-sync]
local = "~/.config/zsh"
use = ["{alias,env,opt,style,mise}.zsh"]
apply = ["source"]

[plugins.cd]
inline = "fuction cd() { builtin cd $@ && ls --color=auto; }"

[plugins.pure]
github = "sindresorhus/pure"
use = ["async.zsh", "pure.zsh"]

[plugins.pure.hooks]
pre = "setopt prompt_subst"

[plugins.oh-my-zsh]
github = "ohmyzsh/ohmyzsh"
dir = "plugins"
use = ["{git,tmux}/*.plugin.zsh"]
apply = ["defer"]

[plugins.oh-my-zsh.hooks]
pre = """
TERM=xterm-256color
ZSH_TMUX_FIXTERM=false
"""

[plugins.zsh-completions]
github = "zsh-users/zsh-completions"
apply = ["defer"]

[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"
use = ["{{ name }}.zsh"]
apply = ["defer"]

[plugins.zsh-syntax-highlighting]
github = "zsh-users/zsh-syntax-highlighting"
apply = ["defer"]

[plugins.zsh-history-substring-search]
github = "zsh-users/zsh-history-substring-search"
use = ["{{ name }}.zsh"]
apply = ["defer"]

[plugins.zsh-vi-mode]
github = "jeffreytse/zsh-vi-mode"
use = ["{{ name }}.zsh"]
apply = ["defer"]

[plugins.zsh-vi-mode.hooks]
post = """
zvm_after_init_commands+=(
  \"bindkey '^P' history-substring-search-up\"
  \"bindkey '^N' history-substring-search-down\"
  \"bindkey -M vicmd '^P' history-substring-search-up\"
  \"bindkey -M vicmd '^N' history-substring-search-down\"
  \"bindkey -M vicmd 'k' history-substring-search-up\"
  \"bindkey -M vicmd 'j' history-substring-search-down\"
)"""

[plugins.fzf]
github = "junegunn/fzf"
apply = ["defer", "fzf-install", "fzf-source"]

[plugins.forgit]
github = "wfxr/forgit"
apply = ["defer"]

[plugins.fzf-tag]
github = "Aloxaf/fzf-tab"
apply = ["defer"]
